# Site settings
title: StrideMob
description: > # this means to ignore newlines until "baseurl:"
  Community Inspired Running, Cycling, Swimming, Triathalon and other events
baseurl: "/stridemob"
url: "http://www.stridemob.com"


# Build settings
markdown: kramdown
